server:
  servlet:
    context-path:
  port: 8082

#MySQL数据库
spring:
  datasource:
    url: jdbc:mysql://139.224.22.145:3306/wan?characterEncoding=utf8&useUnicode=true&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456

#mybatis
mybatis:
  type-aliases-package: wan.com.templateproject
  mapper-locations: classpath:mapper/*Mapper.xml
